-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS user_tasks (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 name TEXT NOT NULL,
 category TEXT NOT NULL,
 sort_order INTEGER DEFAULT 0,
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_tasks_select_own ON user_tasks
 FOR SELECT USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY user_tasks_insert_own ON user_tasks
 FOR INSERT WITH CHECK (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY user_tasks_update_own ON user_tasks
 FOR UPDATE USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY user_tasks_delete_own ON user_tasks
 FOR DELETE USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

-- 插入默认任务模板
INSERT INTO user_tasks (user_id, name, category, sort_order) VALUES
('template', '晨间清洁', 'cleansing', 1),
('template', '涂抹精华', 'skincare', 2),
('template', '防晒护理', 'skincare', 3),
('template', '健康饮食', 'diet', 4),
('template', '充足睡眠', 'sleep', 5),
('template', '适量运动', 'exercise', 6)
ON CONFLICT DO NOTHING;

