-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

INSERT INTO storage.buckets (id, name, public) VALUES (gen_random_uuid(), 'user-avatars', true)
