-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS tips (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 content TEXT NOT NULL,
 category TEXT DEFAULT 'general',
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO tips (content, category) VALUES
('每天饮水2000ml，肌肤更水润', 'general'),
('防晒是抗老第一步，四季都要涂', 'general'),
('洁面后3分钟内涂抹护肤品效果最佳', 'general'),
('每周2次去角质，帮助护肤品吸收', 'general'),
('睡眠不足会导致肌肤暗沉和细纹', 'general'),
('多吃富含维生素C的水果，有助于美白', 'diet'),
('睡前卸妆是护肤的关键步骤', 'cleansing'),
('根据季节更换适合的护肤品', 'skincare')
ON CONFLICT DO NOTHING;

