-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建护肤好文表
CREATE TABLE IF NOT EXISTS skincare_articles (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 content TEXT NOT NULL,
 summary TEXT,
 cover_image TEXT,
 category TEXT,
 tags TEXT[],
 author TEXT,
 read_count INTEGER DEFAULT 0,
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建护肤真实评价表
CREATE TABLE IF NOT EXISTS skincare_reviews (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 user_nickname TEXT,
 user_avatar TEXT,
 product_name TEXT NOT NULL,
 brand TEXT,
 rating INTEGER CHECK (rating >= 1 AND rating <= 5),
 content TEXT NOT NULL,
 images TEXT[],
 likes INTEGER DEFAULT 0,
 is_verified BOOLEAN DEFAULT false,
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 添加RLS策略
ALTER TABLE skincare_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE skincare_reviews ENABLE ROW LEVEL SECURITY;

-- 匿名读取策略
CREATE POLICY anon_select_articles ON skincare_articles FOR SELECT USING (is_active = true);
CREATE POLICY anon_select_reviews ON skincare_reviews FOR SELECT USING (is_active = true);

-- 允许匿名插入评价
CREATE POLICY anon_insert_reviews ON skincare_reviews FOR INSERT WITH CHECK (true);

