-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 启用 RLS
ALTER TABLE public.skin_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.check_in_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_products ENABLE ROW LEVEL SECURITY;

-- 匿名访问策略
CREATE POLICY anon_select_products ON public.products FOR SELECT USING (true);
CREATE POLICY anon_select_skin_reports ON public.skin_reports FOR SELECT USING (true);
CREATE POLICY anon_insert_skin_reports ON public.skin_reports FOR INSERT WITH CHECK (true);
CREATE POLICY anon_select_check_in ON public.check_in_records FOR SELECT USING (true);
CREATE POLICY anon_insert_check_in ON public.check_in_records FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_check_in ON public.check_in_records FOR UPDATE USING (true);
CREATE POLICY anon_select_favorites ON public.user_favorites FOR SELECT USING (true);
CREATE POLICY anon_insert_favorites ON public.user_favorites FOR INSERT WITH CHECK (true);
CREATE POLICY anon_delete_favorites ON public.user_favorites FOR DELETE USING (true);
CREATE POLICY anon_select_user_products ON public.user_products FOR SELECT USING (true);
CREATE POLICY anon_insert_user_products ON public.user_products FOR INSERT WITH CHECK (true);
CREATE POLICY anon_update_user_products ON public.user_products FOR UPDATE USING (true);

-- 存储桶策略
CREATE POLICY anon_select_skin_photos ON storage.objects FOR SELECT USING (bucket_id = 'skin-photos');
CREATE POLICY anon_insert_skin_photos ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'skin-photos');

