-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建存储桶 for 用户上传照片
INSERT INTO storage.buckets (id, name, public)
VALUES ('skin-photos', 'skin-photos', true)
ON CONFLICT (id) DO NOTHING;

-- 肤质报告表
CREATE TABLE IF NOT EXISTS public.skin_reports (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 photo_url TEXT,
 photo_path TEXT,
 total_score INTEGER NOT NULL,
 skin_age INTEGER NOT NULL,
 skin_age_delta INTEGER NOT NULL,
 skin_type TEXT NOT NULL,
 -- 9项肤质指标
 moisture_level INTEGER, -- 水润度 0-100
 oil_level INTEGER, -- 出油度 0-100
 sensitivity_level INTEGER, -- 敏感度 0-100
 acne_level INTEGER, -- 痘痘程度 0-100
 pigmentation_level INTEGER, -- 色斑程度 0-100
 wrinkle_level INTEGER, -- 皱纹程度 0-100
 pore_level INTEGER, -- 毛孔程度 0-100
 dark_circle_level INTEGER, -- 黑眼圈程度 0-100
 smoothness_level INTEGER, -- 光滑度 0-100
 analysis_summary TEXT,
 ai_analysis JSONB DEFAULT '{}',
 user_age INTEGER NOT NULL,
 user_gender TEXT NOT NULL,
 user_age_group TEXT NOT NULL,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 打卡记录表
CREATE TABLE IF NOT EXISTS public.check_in_records (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 date TEXT NOT NULL,
 mood TEXT,
 tasks JSONB DEFAULT '[]',
 progress INTEGER DEFAULT 0,
 completed BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 UNIQUE(user_id, date)
);

-- 产品库表
CREATE TABLE IF NOT EXISTS public.products (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 brand TEXT NOT NULL,
 category TEXT NOT NULL,
 price_min INTEGER NOT NULL,
 price_max INTEGER NOT NULL,
 budget_level TEXT NOT NULL,
 skin_types TEXT[] DEFAULT '{}',
 suitable_age_groups TEXT[] DEFAULT '{}',
 image_url TEXT,
 description TEXT,
 ingredients TEXT[],
 purchase_url TEXT,
 rating DECIMAL(3,2) DEFAULT 0,
 review_count INTEGER DEFAULT 0,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 用户收藏表
CREATE TABLE IF NOT EXISTS public.user_favorites (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 UNIQUE(user_id, product_id)
);

-- 用户产品使用记录
CREATE TABLE IF NOT EXISTS public.user_products (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 product_id UUID NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
 status TEXT DEFAULT 'using', -- using, finished, discontinued
 started_at TIMESTAMPTZ DEFAULT NOW(),
 finished_at TIMESTAMPTZ,
 rating INTEGER,
 notes TEXT,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

