-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, ingredients, rating, review_count) VALUES
('氨基酸温和洁面乳', '芙丽芳丝', 'cleanser', 120, 150, 'mid', ARRAY['dry', 'sensitive', 'normal'], ARRAY['teen', 'adult'], '温和氨基酸配方，深层清洁不紧绷，适合敏感肌使用', ARRAY['氨基酸', '甘油', '神经酰胺'], 4.8, 12580),
('净透控油洁面膏', '资生堂', 'cleanser', 180, 220, 'mid', ARRAY['oily', 'combination'], ARRAY['adult'], '深层清洁毛孔，控油祛痘，清爽不紧绷', ARRAY['水杨酸', '茶树精油', '薄荷'], 4.6, 8920),
('玻尿酸保湿爽肤水', 'Hada Labo', 'toner', 89, 120, 'budget', ARRAY['dry', 'normal', 'sensitive'], ARRAY['teen', 'adult'], '五重玻尿酸深层补水，无香料无酒精，温和保湿', ARRAY['玻尿酸', '神经酰胺', '透明质酸'], 4.7, 25600),
('神仙水护肤精华露', 'SK-II', 'essence', 1200, 1540, 'luxury', ARRAY['oily', 'combination', 'normal'], ARRAY['adult'], 'PITERA™精华调理肌肤，改善肤质，提亮肤色', ARRAY['PITERA', '维生素', '矿物质'], 4.9, 45600),
('小棕瓶修护精华', '雅诗兰黛', 'essence', 850, 1080, 'premium', ARRAY['dry', 'combination', 'normal'], ARRAY['adult'], '夜间修护，抗老紧致，淡化细纹', ARRAY['二裂酵母', '透明质酸', '多肽'], 4.8, 38900),
('维C美白精华液', 'The Ordinary', 'essence', 68, 95, 'budget', ARRAY['normal', 'combination'], ARRAY['adult'], '高浓度维C美白淡斑，提亮肤色', ARRAY['维C', '透明质酸', '熊果苷'], 4.5, 15600),
('高保湿面霜', '科颜氏', 'moisturizer', 280, 320, 'mid', ARRAY['dry', 'sensitive', 'normal'], ARRAY['teen', 'adult'], '24小时长效保湿，修复肌肤屏障', ARRAY['角鲨烷', '冰川蛋白', '神经酰胺'], 4.7, 22300),
('清爽控油乳液', '倩碧', 'moisturizer', 280, 340, 'mid', ARRAY['oily', 'combination'], ARRAY['teen', 'adult'], '无油配方，清爽保湿，控油平衡', ARRAY['透明质酸', '海藻糖', '芦荟'], 4.6, 18700),
('小金瓶防晒霜', '安耐晒', 'sunscreen', 180, 228, 'mid', ARRAY['dry', 'oily', 'combination', 'sensitive', 'normal'], ARRAY['teen', 'adult'], 'SPF50+ PA++++，防水防汗，清爽不油腻', ARRAY['氧化锌', '二氧化钛', '维生素E'], 4.8, 67800),
('水感防晒乳', '碧柔', 'sunscreen', 45, 65, 'budget', ARRAY['oily', 'combination', 'normal'], ARRAY['teen', 'adult'], '水感质地，清爽不黏腻，日常防晒', ARRAY['玻尿酸', '维生素C', '甘油'], 4.5, 34200),
('补水面膜', '美迪惠尔', 'mask', 89, 120, 'budget', ARRAY['dry', 'normal', 'sensitive'], ARRAY['teen', 'adult'], '深层补水，舒缓修护，玻尿酸精华', ARRAY['玻尿酸', '胶原蛋白', '甘油'], 4.6, 28900),
('清洁泥膜', '科颜氏', 'mask', 280, 320, 'mid', ARRAY['oily', 'combination'], ARRAY['adult'], '亚马逊白泥深层清洁，收缩毛孔', ARRAY['白泥', '芦荟', '燕麦'], 4.7, 19800),
('烟酰胺修护精华', 'OLAY', 'essence', 180, 240, 'mid', ARRAY['normal', 'combination', 'oily'], ARRAY['adult'], '烟酰胺美白淡斑，提亮肤色', ARRAY['烟酰胺', '维C', '透明质酸'], 4.6, 45600),
('红腰子精华', '资生堂', 'essence', 680, 860, 'premium', ARRAY['dry', 'sensitive', 'normal'], ARRAY['adult'], '提升肌肤免疫力，修护维稳', ARRAY['灵芝', '鸢尾花', '酵母'], 4.8, 23400),
('粉水舒缓爽肤水', '兰蔻', 'toner', 320, 420, 'premium', ARRAY['dry', 'sensitive', 'normal'], ARRAY['adult'], '温和舒缓，补水保湿，适合干敏肌', ARRAY['蜂蜜', '甜杏仁', '透明质酸'], 4.7, 32100),
('绿茶籽精华', '悦诗风吟', 'essence', 120, 160, 'mid', ARRAY['oily', 'combination'], ARRAY['teen', 'adult'], '绿茶籽萃取，清爽保湿，抗氧化', ARRAY['绿茶籽', '甘油', '维生素E'], 4.5, 18700),
('B5修复霜', '理肤泉', 'moisturizer', 98, 128, 'budget', ARRAY['sensitive', 'dry', 'normal'], ARRAY['teen', 'adult'], '维生素B5修复，舒缓敏感肌', ARRAY['维生素B5', '神经酰胺', '温泉水'], 4.8, 28900),
('蓝胖子防晒', '资生堂', 'sunscreen', 280, 380, 'premium', ARRAY['dry', 'oily', 'combination', 'sensitive', 'normal'], ARRAY['adult'], '遇水则强技术，清爽防晒', ARRAY['氧化锌', '二氧化钛', '玻尿酸'], 4.9, 45600),
('睡眠面膜', '兰芝', 'mask', 180, 220, 'mid', ARRAY['dry', 'normal'], ARRAY['teen', 'adult'], '夜间修护，补水保湿，免洗面膜', ARRAY['玻尿酸', '矿物质水', '维生素E'], 4.6, 23400),
('黑泥清洁面膜', '悦木之源', 'mask', 220, 280, 'mid', ARRAY['oily', 'combination'], ARRAY['adult'], '活性炭深层清洁，吸附黑头', ARRAY['活性炭', '蜂蜜', '芦荟'], 4.7, 15600);

