-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 完美日记 - 洁面乳
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('氨基酸温和洁面乳', '完美日记', 'cleanser', 49, 69, 'budget', ARRAY['normal', 'combination', 'sensitive'], ARRAY['teen', 'young', 'adult'], '氨基酸配方，温和清洁不紧绷，适合年轻肌肤', 4.5, 12000);

-- 花西子 - 防晒
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('小黛伞防晒妆前霜 SPF50+', '花西子', 'sunscreen', 129, 169, 'mid', ARRAY['normal', 'combination', 'dry'], ARRAY['young', 'adult'], '国风防晒，轻薄不搓泥，妆前防晒二合一', 4.6, 8500);

-- colorkey - 精华
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('玻尿酸保湿精华液', 'colorkey', 'essence', 59, 89, 'budget', ARRAY['dry', 'normal', 'combination'], ARRAY['teen', 'young'], '平价玻尿酸精华，深层补水锁水', 4.3, 6000);

-- 橘朵 - 面膜
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('舒缓修护面膜', '橘朵', 'mask', 39, 59, 'ultra_budget', ARRAY['sensitive', 'normal'], ARRAY['teen', 'young'], '平价好用，舒缓修护敏感肌', 4.4, 4500);

-- 薇诺娜 - 乳液
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('舒敏保湿特护霜', '薇诺娜', 'moisturizer', 88, 128, 'mid', ARRAY['sensitive', 'dry'], ARRAY['young', 'adult'], '敏感肌救星，修护屏障', 4.7, 25000);

-- 珀莱雅 - 精华
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('双抗精华2.0', '珀莱雅', 'essence', 239, 329, 'mid', ARRAY['normal', 'combination', 'oily'], ARRAY['young', 'adult'], '抗氧化抗糖化，提亮肤色', 4.6, 18000);

-- 华熙生物 - 爽肤水
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('玻尿酸水光爽肤水', '华熙生物', 'toner', 79, 119, 'budget', ARRAY['dry', 'normal'], ARRAY['young', 'adult'], '玻尿酸大厂出品，深层补水', 4.5, 9000);

-- 敷尔佳 - 面膜
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('医用透明质酸钠修复贴', '敷尔佳', 'mask', 89, 139, 'mid', ARRAY['sensitive', 'acne'], ARRAY['young', 'adult'], '医美级修护面膜，术后可用', 4.8, 35000);

-- 瑷尔博士 - 洁面
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('洁颜蜜氨基酸洁面', '瑷尔博士', 'cleanser', 58, 78, 'budget', ARRAY['normal', 'combination', 'sensitive'], ARRAY['young', 'adult'], '福瑞达出品，益生菌洁面', 4.6, 12000);

-- 溪木源 - 爽肤水
INSERT INTO products (name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, rating, review_count) 
VALUES ('山茶花舒缓爽肤水', '溪木源', 'toner', 69, 99, 'budget', ARRAY['sensitive', 'normal'], ARRAY['teen', 'young'], '山茶花成分，舒缓修护', 4.4, 5500);

