-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 补充 skin_reports 表字段
ALTER TABLE public.skin_reports 
ADD COLUMN IF NOT EXISTS chin_oil_rate INTEGER,
ADD COLUMN IF NOT EXISTS skin_tone TEXT,
ADD COLUMN IF NOT EXISTS undertone TEXT,
ADD COLUMN IF NOT EXISTS wrinkle_score INTEGER,
ADD COLUMN IF NOT EXISTS elasticity_score INTEGER,
ADD COLUMN IF NOT EXISTS pigmentation_score INTEGER,
ADD COLUMN IF NOT EXISTS pore_score INTEGER;

-- 创建问卷表
CREATE TABLE IF NOT EXISTS public.skin_questionnaires (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 report_id UUID REFERENCES public.skin_reports(id) ON DELETE CASCADE,
 -- 肤质自评
 skin_feel TEXT, -- 紧绷/油腻/舒适
 pore_concern TEXT, -- 无/轻微/明显
 sensitivity TEXT, -- 无/偶尔/经常过敏
 -- 生活习惯
 sleep_quality TEXT, -- 好/一般/差
 water_intake TEXT, -- 多/正常/少
 stress_level TEXT, -- 高/中/低
 -- 护肤习惯
 makeup_frequency TEXT, -- 每天/偶尔/从不
 sunscreen_usage TEXT, -- 每天/偶尔/从不
 skincare_routine TEXT, -- 完整/基础/简单
 -- 环境因素
 city_pollution TEXT, -- 高/中/低
 work_environment TEXT, -- 户外/室内空调/室内正常
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.skin_questionnaires ENABLE ROW LEVEL SECURITY;
CREATE POLICY anon_select_questionnaires ON public.skin_questionnaires FOR SELECT USING (true);
CREATE POLICY anon_insert_questionnaires ON public.skin_questionnaires FOR INSERT WITH CHECK (true);

