-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS user_profiles (
 id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
 nickname TEXT,
 avatar TEXT,
 skin_type TEXT DEFAULT 'combination',
 budget_level TEXT DEFAULT 'mid',
 age INTEGER DEFAULT 25,
 gender TEXT DEFAULT 'female',
 age_group TEXT DEFAULT 'adult',
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY user_profiles_select_own ON user_profiles
 FOR SELECT USING (auth.uid() = id);

CREATE POLICY user_profiles_insert_own ON user_profiles
 FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY user_profiles_update_own ON user_profiles
 FOR UPDATE USING (auth.uid() = id);

