-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS ai_service_configs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 service_type TEXT NOT NULL, -- image_gen, text_gen, vision
 provider TEXT NOT NULL, -- meoo, openai, stability, etc.
 name TEXT NOT NULL,
 api_key TEXT,
 base_url TEXT,
 model TEXT,
 is_active BOOLEAN DEFAULT false,
 is_default BOOLEAN DEFAULT false,
 config JSONB DEFAULT '{}',
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE ai_service_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY ai_service_configs_select_own ON ai_service_configs
 FOR SELECT USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY ai_service_configs_insert_own ON ai_service_configs
 FOR INSERT WITH CHECK (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY ai_service_configs_update_own ON ai_service_configs
 FOR UPDATE USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

CREATE POLICY ai_service_configs_delete_own ON ai_service_configs
 FOR DELETE USING (user_id = auth.uid()::text OR user_id LIKE 'guest-%');

-- 插入默认Meoo配置
INSERT INTO ai_service_configs (user_id, service_type, provider, name, base_url, model, is_active, is_default, config) VALUES
('default', 'image_gen', 'meoo', 'Meoo AI生图', 'https://api.meoo.host', 'wan2.7-image', true, true, '{"size": "2K", "watermark": false}'),
('default', 'text_gen', 'meoo', 'Meoo AI文本', 'https://api.meoo.host', 'qwen3.6-plus', true, true, '{}'),
('default', 'vision', 'meoo', 'Meoo AI视觉', 'https://api.meoo.host', 'qwen3-vl-plus', true, true, '{}')
ON CONFLICT DO NOTHING;

