-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


INSERT INTO products (id, name, brand, category, price_min, price_max, budget_level, skin_types, suitable_age_groups, description, ingredients, rating, review_count, created_at)
VALUES (
 gen_random_uuid(),
 '可复美吨吨水乳套装',
 '可复美',
 'moisturizer',
 159,
 299,
 'mid',
 ARRAY['dry', 'combination', 'sensitive', 'normal'],
 ARRAY['teen', 'adult'],
 '透明质酸钠藻萃盈润保湿精华水乳套装，深层补水锁水，适合干燥缺水肌肤，清爽不油腻',
 ARRAY['透明质酸钠', '藻萃提取物', '甘油', '神经酰胺', '泛醇'],
 4.6,
 8500,
 NOW()
);

