-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建护肤方案表
CREATE TABLE IF NOT EXISTS skincare_routines (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 name TEXT NOT NULL DEFAULT '我的护肤方案',
 description TEXT,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建护肤步骤表
CREATE TABLE IF NOT EXISTS routine_steps (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 routine_id UUID REFERENCES skincare_routines(id) ON DELETE CASCADE,
 user_product_id UUID REFERENCES user_products(id) ON DELETE CASCADE,
 step_order INTEGER NOT NULL,
 time_of_day TEXT NOT NULL CHECK (time_of_day IN ('morning', 'evening', 'both')),
 usage_amount TEXT,
 usage_instructions TEXT,
 wait_time_minutes INTEGER DEFAULT 0,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建使用记录表
CREATE TABLE IF NOT EXISTS usage_logs (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id TEXT NOT NULL,
 user_product_id UUID REFERENCES user_products(id) ON DELETE CASCADE,
 used_at TIMESTAMPTZ DEFAULT NOW(),
 notes TEXT,
 satisfaction INTEGER CHECK (satisfaction >= 1 AND satisfaction <= 5)
);

-- 启用RLS
ALTER TABLE skincare_routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE routine_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_logs ENABLE ROW LEVEL SECURITY;

-- 添加RLS策略
CREATE POLICY anon_all_skincare_routines ON skincare_routines FOR ALL USING (true);
CREATE POLICY anon_all_routine_steps ON routine_steps FOR ALL USING (true);
CREATE POLICY anon_all_usage_logs ON usage_logs FOR ALL USING (true);

