// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ai_service_configs: {
        Row: {
          api_key: string | null
          base_url: string | null
          config: Json | null
          created_at: string | null
          id: string
          is_active: boolean | null
          is_default: boolean | null
          model: string | null
          name: string
          provider: string
          service_type: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          api_key?: string | null
          base_url?: string | null
          config?: Json | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          is_default?: boolean | null
          model?: string | null
          name: string
          provider: string
          service_type: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          api_key?: string | null
          base_url?: string | null
          config?: Json | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          is_default?: boolean | null
          model?: string | null
          name?: string
          provider?: string
          service_type?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      check_in_records: {
        Row: {
          completed: boolean | null
          created_at: string | null
          date: string
          id: string
          mood: string | null
          progress: number | null
          tasks: Json | null
          user_id: string
        }
        Insert: {
          completed?: boolean | null
          created_at?: string | null
          date: string
          id?: string
          mood?: string | null
          progress?: number | null
          tasks?: Json | null
          user_id: string
        }
        Update: {
          completed?: boolean | null
          created_at?: string | null
          date?: string
          id?: string
          mood?: string | null
          progress?: number | null
          tasks?: Json | null
          user_id?: string
        }
        Relationships: []
      }
      products: {
        Row: {
          brand: string
          budget_level: string
          category: string
          created_at: string | null
          description: string | null
          id: string
          image_url: string | null
          ingredients: string[] | null
          name: string
          price_max: number
          price_min: number
          purchase_url: string | null
          rating: number | null
          review_count: number | null
          skin_types: string[] | null
          suitable_age_groups: string[] | null
        }
        Insert: {
          brand: string
          budget_level: string
          category: string
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          ingredients?: string[] | null
          name: string
          price_max: number
          price_min: number
          purchase_url?: string | null
          rating?: number | null
          review_count?: number | null
          skin_types?: string[] | null
          suitable_age_groups?: string[] | null
        }
        Update: {
          brand?: string
          budget_level?: string
          category?: string
          created_at?: string | null
          description?: string | null
          id?: string
          image_url?: string | null
          ingredients?: string[] | null
          name?: string
          price_max?: number
          price_min?: number
          purchase_url?: string | null
          rating?: number | null
          review_count?: number | null
          skin_types?: string[] | null
          suitable_age_groups?: string[] | null
        }
        Relationships: []
      }
      routine_steps: {
        Row: {
          created_at: string | null
          id: string
          routine_id: string | null
          step_order: number
          time_of_day: string
          usage_amount: string | null
          usage_instructions: string | null
          user_product_id: string | null
          wait_time_minutes: number | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          routine_id?: string | null
          step_order: number
          time_of_day: string
          usage_amount?: string | null
          usage_instructions?: string | null
          user_product_id?: string | null
          wait_time_minutes?: number | null
        }
        Update: {
          created_at?: string | null
          id?: string
          routine_id?: string | null
          step_order?: number
          time_of_day?: string
          usage_amount?: string | null
          usage_instructions?: string | null
          user_product_id?: string | null
          wait_time_minutes?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "routine_steps_routine_id_fkey"
            columns: ["routine_id"]
            referencedRelation: "skincare_routines"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "routine_steps_user_product_id_fkey"
            columns: ["user_product_id"]
            referencedRelation: "user_products"
            referencedColumns: ["id"]
          },
        ]
      }
      skin_questionnaires: {
        Row: {
          city_pollution: string | null
          created_at: string | null
          id: string
          makeup_frequency: string | null
          pore_concern: string | null
          report_id: string | null
          sensitivity: string | null
          skin_feel: string | null
          skincare_routine: string | null
          sleep_quality: string | null
          stress_level: string | null
          sunscreen_usage: string | null
          user_id: string
          water_intake: string | null
          work_environment: string | null
        }
        Insert: {
          city_pollution?: string | null
          created_at?: string | null
          id?: string
          makeup_frequency?: string | null
          pore_concern?: string | null
          report_id?: string | null
          sensitivity?: string | null
          skin_feel?: string | null
          skincare_routine?: string | null
          sleep_quality?: string | null
          stress_level?: string | null
          sunscreen_usage?: string | null
          user_id: string
          water_intake?: string | null
          work_environment?: string | null
        }
        Update: {
          city_pollution?: string | null
          created_at?: string | null
          id?: string
          makeup_frequency?: string | null
          pore_concern?: string | null
          report_id?: string | null
          sensitivity?: string | null
          skin_feel?: string | null
          skincare_routine?: string | null
          sleep_quality?: string | null
          stress_level?: string | null
          sunscreen_usage?: string | null
          user_id?: string
          water_intake?: string | null
          work_environment?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "skin_questionnaires_report_id_fkey"
            columns: ["report_id"]
            referencedRelation: "skin_reports"
            referencedColumns: ["id"]
          },
        ]
      }
      skin_reports: {
        Row: {
          acne_level: number | null
          ai_analysis: Json | null
          analysis_summary: string | null
          chin_oil_rate: number | null
          created_at: string | null
          dark_circle_level: number | null
          elasticity_score: number | null
          id: string
          moisture_level: number | null
          oil_level: number | null
          photo_path: string | null
          photo_url: string | null
          pigmentation_level: number | null
          pigmentation_score: number | null
          pore_level: number | null
          pore_score: number | null
          sensitivity_level: number | null
          skin_age: number
          skin_age_delta: number
          skin_tone: string | null
          skin_type: string
          smoothness_level: number | null
          total_score: number
          undertone: string | null
          user_age: number
          user_age_group: string
          user_gender: string
          user_id: string
          wrinkle_level: number | null
          wrinkle_score: number | null
        }
        Insert: {
          acne_level?: number | null
          ai_analysis?: Json | null
          analysis_summary?: string | null
          chin_oil_rate?: number | null
          created_at?: string | null
          dark_circle_level?: number | null
          elasticity_score?: number | null
          id?: string
          moisture_level?: number | null
          oil_level?: number | null
          photo_path?: string | null
          photo_url?: string | null
          pigmentation_level?: number | null
          pigmentation_score?: number | null
          pore_level?: number | null
          pore_score?: number | null
          sensitivity_level?: number | null
          skin_age: number
          skin_age_delta: number
          skin_tone?: string | null
          skin_type: string
          smoothness_level?: number | null
          total_score: number
          undertone?: string | null
          user_age: number
          user_age_group: string
          user_gender: string
          user_id: string
          wrinkle_level?: number | null
          wrinkle_score?: number | null
        }
        Update: {
          acne_level?: number | null
          ai_analysis?: Json | null
          analysis_summary?: string | null
          chin_oil_rate?: number | null
          created_at?: string | null
          dark_circle_level?: number | null
          elasticity_score?: number | null
          id?: string
          moisture_level?: number | null
          oil_level?: number | null
          photo_path?: string | null
          photo_url?: string | null
          pigmentation_level?: number | null
          pigmentation_score?: number | null
          pore_level?: number | null
          pore_score?: number | null
          sensitivity_level?: number | null
          skin_age?: number
          skin_age_delta?: number
          skin_tone?: string | null
          skin_type?: string
          smoothness_level?: number | null
          total_score?: number
          undertone?: string | null
          user_age?: number
          user_age_group?: string
          user_gender?: string
          user_id?: string
          wrinkle_level?: number | null
          wrinkle_score?: number | null
        }
        Relationships: []
      }
      skincare_articles: {
        Row: {
          author: string | null
          category: string | null
          content: string
          cover_image: string | null
          created_at: string | null
          id: string
          is_active: boolean | null
          read_count: number | null
          summary: string | null
          tags: string[] | null
          title: string
          updated_at: string | null
        }
        Insert: {
          author?: string | null
          category?: string | null
          content: string
          cover_image?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          read_count?: number | null
          summary?: string | null
          tags?: string[] | null
          title: string
          updated_at?: string | null
        }
        Update: {
          author?: string | null
          category?: string | null
          content?: string
          cover_image?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          read_count?: number | null
          summary?: string | null
          tags?: string[] | null
          title?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      skincare_reviews: {
        Row: {
          brand: string | null
          content: string
          created_at: string | null
          id: string
          images: string[] | null
          is_active: boolean | null
          is_verified: boolean | null
          likes: number | null
          product_name: string
          rating: number | null
          user_avatar: string | null
          user_id: string
          user_nickname: string | null
        }
        Insert: {
          brand?: string | null
          content: string
          created_at?: string | null
          id?: string
          images?: string[] | null
          is_active?: boolean | null
          is_verified?: boolean | null
          likes?: number | null
          product_name: string
          rating?: number | null
          user_avatar?: string | null
          user_id: string
          user_nickname?: string | null
        }
        Update: {
          brand?: string | null
          content?: string
          created_at?: string | null
          id?: string
          images?: string[] | null
          is_active?: boolean | null
          is_verified?: boolean | null
          likes?: number | null
          product_name?: string
          rating?: number | null
          user_avatar?: string | null
          user_id?: string
          user_nickname?: string | null
        }
        Relationships: []
      }
      skincare_routines: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          name: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          name?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: []
      }
      tips: {
        Row: {
          category: string | null
          content: string
          created_at: string | null
          id: string
          is_active: boolean | null
        }
        Insert: {
          category?: string | null
          content: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
        }
        Update: {
          category?: string | null
          content?: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
        }
        Relationships: []
      }
      usage_logs: {
        Row: {
          id: string
          notes: string | null
          satisfaction: number | null
          used_at: string | null
          user_id: string
          user_product_id: string | null
        }
        Insert: {
          id?: string
          notes?: string | null
          satisfaction?: number | null
          used_at?: string | null
          user_id: string
          user_product_id?: string | null
        }
        Update: {
          id?: string
          notes?: string | null
          satisfaction?: number | null
          used_at?: string | null
          user_id?: string
          user_product_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "usage_logs_user_product_id_fkey"
            columns: ["user_product_id"]
            referencedRelation: "user_products"
            referencedColumns: ["id"]
          },
        ]
      }
      user_favorites: {
        Row: {
          created_at: string | null
          id: string
          product_id: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          product_id: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          product_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_favorites_product_id_fkey"
            columns: ["product_id"]
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      user_products: {
        Row: {
          created_at: string | null
          finished_at: string | null
          id: string
          notes: string | null
          product_id: string
          rating: number | null
          started_at: string | null
          status: string | null
          user_id: string
        }
        Insert: {
          created_at?: string | null
          finished_at?: string | null
          id?: string
          notes?: string | null
          product_id: string
          rating?: number | null
          started_at?: string | null
          status?: string | null
          user_id: string
        }
        Update: {
          created_at?: string | null
          finished_at?: string | null
          id?: string
          notes?: string | null
          product_id?: string
          rating?: number | null
          started_at?: string | null
          status?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_products_product_id_fkey"
            columns: ["product_id"]
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          age: number | null
          age_group: string | null
          avatar: string | null
          budget_level: string | null
          created_at: string | null
          gender: string | null
          id: string
          nickname: string | null
          skin_type: string | null
          updated_at: string | null
        }
        Insert: {
          age?: number | null
          age_group?: string | null
          avatar?: string | null
          budget_level?: string | null
          created_at?: string | null
          gender?: string | null
          id: string
          nickname?: string | null
          skin_type?: string | null
          updated_at?: string | null
        }
        Update: {
          age?: number | null
          age_group?: string | null
          avatar?: string | null
          budget_level?: string | null
          created_at?: string | null
          gender?: string | null
          id?: string
          nickname?: string | null
          skin_type?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      user_tasks: {
        Row: {
          category: string
          created_at: string | null
          id: string
          is_active: boolean | null
          name: string
          sort_order: number | null
          user_id: string
        }
        Insert: {
          category: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          sort_order?: number | null
          user_id: string
        }
        Update: {
          category?: string
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          sort_order?: number | null
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      binary_quantize: {
        Args: { "": string } | { "": unknown }
        Returns: unknown
      }
      halfvec_avg: {
        Args: { "": number[] }
        Returns: unknown
      }
      halfvec_out: {
        Args: { "": unknown }
        Returns: unknown
      }
      halfvec_send: {
        Args: { "": unknown }
        Returns: string
      }
      halfvec_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
      hnsw_bit_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_halfvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_rdsvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnsw_sparsevec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      hnswhandler: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflat_bit_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflat_halfvec_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfflathandler: {
        Args: { "": unknown }
        Returns: unknown
      }
      ivfrabitq_vector_support: {
        Args: { "": unknown }
        Returns: unknown
      }
      l2_norm: {
        Args: { "": unknown } | { "": unknown }
        Returns: number
      }
      l2_normalize: {
        Args: { "": string } | { "": unknown } | { "": unknown }
        Returns: unknown
      }
      rds_float_normalize_i16: {
        Args: { "": unknown }
        Returns: unknown
      }
      rds_vector_norm: {
        Args: { "": string }
        Returns: number
      }
      sparsevec_out: {
        Args: { "": unknown }
        Returns: unknown
      }
      sparsevec_send: {
        Args: { "": unknown }
        Returns: string
      }
      sparsevec_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
      vector_avg: {
        Args: { "": number[] }
        Returns: string
      }
      vector_dims: {
        Args: { "": string } | { "": unknown }
        Returns: number
      }
      vector_norm: {
        Args: { "": string }
        Returns: number
      }
      vector_out: {
        Args: { "": string }
        Returns: unknown
      }
      vector_send: {
        Args: { "": string }
        Returns: string
      }
      vector_typmod_in: {
        Args: { "": unknown[] }
        Returns: number
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
