/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SkinTestRouteImport } from './routes/skin-test'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PriceCompareRouteImport } from './routes/price-compare'
import { Route as MyRoutineRouteImport } from './routes/my-routine'
import { Route as MyProductsRouteImport } from './routes/my-products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as BeautyTransformRouteImport } from './routes/beauty-transform'
import { Route as AiConfigRouteImport } from './routes/ai-config'
import { Route as IndexRouteImport } from './routes/index'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinTestRoute = SkinTestRouteImport.update({
  id: '/skin-test',
  path: '/skin-test',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceCompareRoute = PriceCompareRouteImport.update({
  id: '/price-compare',
  path: '/price-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoutineRoute = MyRoutineRouteImport.update({
  id: '/my-routine',
  path: '/my-routine',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProductsRoute = MyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautyTransformRoute = BeautyTransformRouteImport.update({
  id: '/beauty-transform',
  path: '/beauty-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const AiConfigRoute = AiConfigRouteImport.update({
  id: '/ai-config',
  path: '/ai-config',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/beauty-transform': typeof BeautyTransformRoute
  '/check-in': typeof CheckInRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/my-routine': typeof MyRoutineRoute
  '/price-compare': typeof PriceCompareRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/recommend': typeof RecommendRoute
  '/skin-test': typeof SkinTestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/beauty-transform': typeof BeautyTransformRoute
  '/check-in': typeof CheckInRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/my-routine': typeof MyRoutineRoute
  '/price-compare': typeof PriceCompareRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/recommend': typeof RecommendRoute
  '/skin-test': typeof SkinTestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-config': typeof AiConfigRoute
  '/beauty-transform': typeof BeautyTransformRoute
  '/check-in': typeof CheckInRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/my-products': typeof MyProductsRoute
  '/my-routine': typeof MyRoutineRoute
  '/price-compare': typeof PriceCompareRoute
  '/profile': typeof ProfileRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/recommend': typeof RecommendRoute
  '/skin-test': typeof SkinTestRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-config'
    | '/beauty-transform'
    | '/check-in'
    | '/invite'
    | '/login'
    | '/my-products'
    | '/my-routine'
    | '/price-compare'
    | '/profile'
    | '/questionnaire'
    | '/recommend'
    | '/skin-test'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-config'
    | '/beauty-transform'
    | '/check-in'
    | '/invite'
    | '/login'
    | '/my-products'
    | '/my-routine'
    | '/price-compare'
    | '/profile'
    | '/questionnaire'
    | '/recommend'
    | '/skin-test'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/ai-config'
    | '/beauty-transform'
    | '/check-in'
    | '/invite'
    | '/login'
    | '/my-products'
    | '/my-routine'
    | '/price-compare'
    | '/profile'
    | '/questionnaire'
    | '/recommend'
    | '/skin-test'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiConfigRoute: typeof AiConfigRoute
  BeautyTransformRoute: typeof BeautyTransformRoute
  CheckInRoute: typeof CheckInRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  MyProductsRoute: typeof MyProductsRoute
  MyRoutineRoute: typeof MyRoutineRoute
  PriceCompareRoute: typeof PriceCompareRoute
  ProfileRoute: typeof ProfileRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  RecommendRoute: typeof RecommendRoute
  SkinTestRoute: typeof SkinTestRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-test': {
      id: '/skin-test'
      path: '/skin-test'
      fullPath: '/skin-test'
      preLoaderRoute: typeof SkinTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-compare': {
      id: '/price-compare'
      path: '/price-compare'
      fullPath: '/price-compare'
      preLoaderRoute: typeof PriceCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-routine': {
      id: '/my-routine'
      path: '/my-routine'
      fullPath: '/my-routine'
      preLoaderRoute: typeof MyRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-products': {
      id: '/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof MyProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-transform': {
      id: '/beauty-transform'
      path: '/beauty-transform'
      fullPath: '/beauty-transform'
      preLoaderRoute: typeof BeautyTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-config': {
      id: '/ai-config'
      path: '/ai-config'
      fullPath: '/ai-config'
      preLoaderRoute: typeof AiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiConfigRoute: AiConfigRoute,
  BeautyTransformRoute: BeautyTransformRoute,
  CheckInRoute: CheckInRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  MyProductsRoute: MyProductsRoute,
  MyRoutineRoute: MyRoutineRoute,
  PriceCompareRoute: PriceCompareRoute,
  ProfileRoute: ProfileRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  RecommendRoute: RecommendRoute,
  SkinTestRoute: SkinTestRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
